### ISSUE TITLE
Negative Betting in the Arena

### ISSUE THREAD

**Issue by KaiserPodge** [capSAR273/TheWastes#10]
Version 0.6.6
You can bet negative values in an arena fight.  If you fail you will gain the value, if you succeed you will lose double the value.  Potentially can be abused when at low coin value.

![bug6](https://cloud.githubusercontent.com/assets/13228951/8561615/bb60c34a-24ed-11e5-90f5-ca35bb7a4857.png)

**Comment by Huw2k8** [comment]
Wow, well spotted, gonna patch that right now

**Comment by capSAR273** [comment]
Yikes!

**Comment by Huw2k8** [comment]
Actually this bug was already patched, think you might be using an older version
