### ISSUE TITLE
Wall of Bones making Music?

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#11]
The text I came across was: 

"You come across a wall of bones, the mere sight of it is enough to make anyone sick"
The game has me choose:
1. Listen to his music
2. Attack
0. Leave

I think I found the secret feature but is it intended to be a wall of bones?

**Comment by Huw2k8** [comment]
Yup, the encounter is supposed to be a wasteland bard but the text is wrong, stupid bug, well found you've been credited in the latest update and updated on the wasteland guide suggestion and bug chart as the bug has been fixed in the latest version 0.6.8
