### ISSUE TITLE
Standardize Menus

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#15]
So far, I see 0 and 4 being used to exit an encounter. It would enhance things if there could be only one way to "leave".

**Comment by Huw2k8** [comment]
I agree, 0 should be used to leave as standard, its hard to keep track of them all though, let me know the non 0 leave options you find

**Comment by capSAR273** [comment]
Other examples:
-  Coming across a locked door (chests work fine with 0 as leave): 1) Lockpick, or 2) Move On 
-  Random monster encounter: 1)attack, 2) Wep attack, 4) Flee
-  Random Dungeon encounter: 1) Enter 2) Move on
-  Man pushing trolley selling food and water, 4 is the option to "Ignore" which leaves

**Comment by Huw2k8** [comment]
changed the flee in combat to be 0 as of latest version
haven't don the other yet though so keep this open

**Comment by Huw2k8** [comment]
this is sort of difficult now that 0 is inventory
