### ISSUE TITLE
Impossible to flee

### ISSUE THREAD

**Issue by jamesay14** [capSAR273/TheWastes#16]
I attempt to flee from a battle, against the final man, but every time I succeed, i am still in battle as if I had failed.

**Comment by Huw2k8** [comment]
Final man? where was this encounter?

Also what version of the game do you have currently because an escape bug was fixed a few version ago

**Comment by jamesay14** [comment]
At the time, I had the 07/07/15 release version. This happened twice, once in an encounter with tribals. I fled ten or so, but the last man was impossible to flee, even if I "managed to escape", it would keep me in the same fight. The exact same thing happened when I was fighting wasps in a random encounter.

**Comment by capSAR273** [comment]
I never encountered this bug, weird. So far I haven't seen it in the most recent version either.

**Comment by jamesay14** [comment]
I just got the daily, I'll try to see if I can recreate it in the newest version.

**Comment by Huw2k8** [comment]
Awesome, keep us posted, Hopefully it was already fixed

**Comment by Huw2k8** [comment]
Assuming it's fixed because it hasnt been reported at all since the new updates have been put out
