### ISSUE TITLE
Regrowth Perk not applied when Damaged

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#17]
In combat, if the enemy damages the player for 1HP, and they have one level of Regrowth, it still damages the player that 1HP. Wouldn't it be negated if Regrowth was applied every turn? I'm not sure if this is the only instance where it doesn't get applied but this was the first one I saw.

**Comment by Huw2k8** [comment]
I shall investigate, that is very strange, don't close this

**Comment by Huw2k8** [comment]
I have checked, regrowth wasn't coded to work at all during combat as far as I could tell, I have changed that, also most mutations that have per turn effects will also still work, ie Bloodboil, Skullrot, Brainrot, SearingSkinrot and Toughening
