### ISSUE TITLE
Add Lockpics to status screen

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#18]
Is this in the grand plan for the inventory system? If not having them under Money would be nice to keep track of, or have a message telling the player how many lockpicks they have left after an attempt.

**Comment by Huw2k8** [comment]
Yeah it really is playing in the dark, they will be displayed in the inventory system but also having them displayed on the menu somewhere will happen soon

**Comment by Huw2k8** [comment]
done as of 0.7
