### ISSUE TITLE
Paying the toll doesn't decrease Money, doesn't have a cost.

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#19]
Maybe this isn't implemented yet but when you have the three dialogue option, "I go where I please", "I got with the winds", "I will pay the toll", the toll doesn't say the cost and doesn't decrease the player's money.

**Comment by Huw2k8** [comment]
definitely need to sort this out soon, it's on my list

**Comment by Huw2k8** [comment]
done
