### ISSUE TITLE
Put Lockpick number below money or XP

### ISSUE THREAD

**Issue by capSAR273** [capSAR273/TheWastes#23]
Maybe it was just misplaced? But I feel like you wouldn't want to put Lockpicks at the very top of the screen :D

**Comment by Huw2k8** [comment]
The problem was that putting it below the money or xp on its own line would make the menu bigger, so I slotted it into the ---------- that was already there so the menu didn't become too bloated, if you can think of any workaround let me know

**Comment by capSAR273** [comment]
Is the menu not modular? I can see now how it would fit in to the top row, kindof like a status bar, but I don't think it would make the menu too bloated if another line was added.

**Comment by capSAR273** [comment]
Maybe just as a temp fix until the inventory system is out. OR, what if you had lockpick number only displayed when you were faced with a lock? That way it would stay out of the way until the player needed to know how much they have.

**Comment by Huw2k8** [comment]
done
