### ISSUE TITLE
Tri-Dragon tail seems to do less damage than intended

### ISSUE THREAD

**Issue by Smilge** [capSAR273/TheWastes#26]
Enemy with 107 HP, I miss and my tri-dragon tail swings for 250, enemy has 7 HP remaining. I'm level 10, so it seems like instead of the displayed 25 damage per level it was only doing 10 damage per level. Not sure if it matters but I got the mutations one after the other very early in the game.

**Comment by Huw2k8** [comment]
You are right! it does 10\* dmg instead of the promised 25*, Shall be fixed in tonights update! thanks
