### ISSUE TITLE
Durable skill is just too OP

### ISSUE THREAD

**Issue by BrPetrus** [capSAR273/TheWastes#28]
In one of my play-through I levelled up the durable skill(or how is it called) and permanently got weapons with 19000+ durability. What's the point of repairing the weapon then :D?
![lootjoke1png - copy](https://cloud.githubusercontent.com/assets/12988110/8836362/aca8e25e-30c0-11e5-9402-4153b4a9577d.png)

**Comment by Huw2k8** [comment]
Durable is nothing to do with the size of the durability number, it just changes the frequency that durability drops when you hit things
