### ISSUE TITLE
Locked crates unlock themselves

### ISSUE THREAD

**Issue by Smilge** [capSAR273/TheWastes#32]
As you can see, I hit "move on" and the crate ended up opening anyways.

![](http://i.imgur.com/69Fjdxm.png)

It seems to have to do with successfully using autopick on an earlier door/crate/etc. but I'm not quite sure.

**Comment by Huw2k8** [comment]
Well spotted, the only way I can explain this is that you had previously unlocked something and the unlocked code never reset, I have since put something in place to reset the locked unlocked variable to prevent this!
