### ISSUE TITLE
Bug on the weapon menu

### ISSUE THREAD

**Issue by DataTriny** [capSAR273/TheWastes#39]
![thewasteserror](https://cloud.githubusercontent.com/assets/11966864/10411282/f105b700-6f5f-11e5-8f62-b272412ee22e.png)
I've tried to drop this weapon, but i'm not allowed to press "4". The interval of allowed numbers should be 1-4, not 0-3.

**Comment by Huw2k8** [comment]
Yup, I noticed that earlier, It should be 0-4 not 0-3
