### ISSUE TITLE
Display after selecting Perks 10 or greater

### ISSUE THREAD

**Issue by KaiserPodge** [capSAR273/TheWastes#7]
After choosing a perk with two characters (10 or greater), it does not clear the display and put the usual status information in the top section.  Third occurrence across two runs where I selected 12, 15, or 16.

![bug2](https://cloud.githubusercontent.com/assets/13228951/8561021/47e7778c-24e4-11e5-8561-978e6bfc94d5.png)

**Comment by Huw2k8** [comment]
should be Fixed in 0.6.7
