### ISSUE TITLE
Buying Mines

### ISSUE THREAD

**Issue by KaiserPodge** [capSAR273/TheWastes#9]
Version: 0.6.6
I'm not sure the effect of buying a mine, but before mining the price tag was 2200ish.  After I stopped mining (nothing forced me to stop), it now tells me it is depleted (834 silver).  The buying price is now negative and I can keep 'buying' the mine for free coins..

![bug5](https://cloud.githubusercontent.com/assets/13228951/8561413/76cf86d8-24ea-11e5-90ab-b61e64f2d479.png)

**Comment by Huw2k8** [comment]
Yup this is a bug, there are many surrounding the mines at the moment because of a big issue with editing town files, once the town files thing is sorted all of these bugs will be wiped out, but I will keep this open for the moment because the bug still exists
